### PR TITLE
Bump to version 0.2.10.0

### PR DESCRIPTION
**Pull request by jamiefolsom**
Hi again @begriffs,

Just a friendly PR to bump the version for the heroku crowd to 0.2.10.0.

Out of curiosity, does 0.2.10.0 differ from 0.2.6.0 in terms of how it handles the --secure flag, or lack thereof?

Thanks!

Jamie

### CODE REVIEW

**Comment by begriffs** [comment]
I think they both do the same thing with the secure flag: redirect all traffic to https.

**Comment by jamiefolsom** [comment]
Hm. I seem to be getting SSL redirects even without the secure flag. I'll poke around. Thanks!

**Comment by begriffs** [comment]
If you're testing the urls with Chrome you may be using a plugin like HTTPS Everywhere. Otherwise try running postgrest without the secure flag and then `curl -I http://yourserver.com` to see if it is returning a 301.

**Comment by jamiefolsom** [comment]
I am using Chrome, but not HTTPS everywhere. I think heroku is redirecting to https automatically. curl requests sent to https:// return 200 and those to http:// return 301. Not using the --secure flag. Odd.

**Pull request merged**
