### PR TITLE
Update Postgrest revision

### PR DESCRIPTION
**Pull request by gRoussac**
Update Postgrest revision for the Heroku buildpack

### CODE REVIEW

**Review by steve-chavez — APPROVED** [review]
LGTM! Thanks!

**Comment by gRoussac** [comment]
@steve-chavez Not sure it was right, and probably readme need to be updated too

```
remote: Building source:
remote:
remote: -----> Building on the Heroku-20 stack
remote: -----> Using buildpack: https://github.com/PostgREST/postgrest-heroku
remote: -----> PostgREST app detected
remote: -----> Exporting config vars
remote:        DB_ANON_ROLE
remote:        DB_SCHEMA
remote:        DB_URI
remote: -----> Downloading and caching libraries for PostgREST
remote: ######################################################################## 100.0%
remote: -----> Could not find prebuilt postgrest-9.0.1
remote:  !     Push rejected, failed to compile PostgREST app.
remote:

```

Do you know what does mean ' Could not find prebuilt postgrest-9.0.1' maybe ?

regards

**Comment by gRoussac** [comment]
@steve-chavez It seems there is a little nomenclature trick here

postgrest-v9.0.1-linux-static-x64.tar.xz

while 

postgrest-v7.0.1-linux-x64-static.tar.xz

😅 falls in line https://github.com/PostgREST/postgrest-heroku/blob/2e89f28e67337169c8aa604d9b43f618fa09e342/bin/compile#L99

Wasn't expecting this sorry ! You need to add a if statement above to handle the inversion !

**Comment by steve-chavez** [comment]
> linux-static-x64
> linux-x64-static

Oh, that is subtle. We'd need to change these lines then https://github.com/PostgREST/postgrest-heroku/blob/main/bin/compile#L83-L87

**Comment by gRoussac** [comment]
Let's try that ?

https://github.com/PostgREST/postgrest-heroku/pull/37

Thanks

**Pull request merged**
